### Method Householder to solve non-linear system

In [194]:

import numpy as np

In [195]:
def house(x):
    n=len(x); mu=np.linalg.norm(x); v=np.copy(x)
    if mu:
        beta=x[0]+(1.0 if x[0] >= 0 else -1.0)*mu
        v[1:]/=beta
    v[0]=1.0
    return v


In [196]:
def row_house(A,v):
    beta = -2.0 / np.dot(v,v)
    w = beta * np.matmul(A.T,v)
    A+=np.outer(v,w)


In [197]:
def house_rev_accum(A,B):
    m,n=A.shape
    v=np.zeros(m)
    for j in range(n-1,-1,-1):
        v[j]=1.0; v[j+1:]=A[j+1:,j]
        row_house(B[j:,j:],v[j:])


In [198]:
def house_QR(A):
    m,n=A.shape
    for j in range(n):
        v=house(A[j:,j])
        row_house(A[j:,j:],v)
        if j<m-1:
            A[j+1:,j]=v[1:]
    return A    
            
# A=np.array([[1, 2, 3, 4], [7, 8, 9, 10], [12, 13, 14, 15], [16, 17, 18, 19],[19, 20, 21, 22]],dtype = 'float64')
# print(house_QR(A))

# m,n=A.shape
# Q=np.eye(m)
# house_rev_accum(A,Q)
# R=np.zeros((m,n))
# for j in range(n):
#     R[:j+1,j]=A[:j+1,j]
# display(Q@R)

[[-2.84780617e+01 -3.04093729e+01 -3.23406842e+01 -3.42719954e+01]
 [ 2.37464731e-01 -1.12695918e+00 -2.25391836e+00 -3.38087754e+00]
 [ 4.07082396e-01 -1.35081707e-01  2.09476461e-15  4.23660259e-15]
 [ 5.42776528e-01 -4.13066445e-01  5.24751609e-01 -4.10004660e-15]
 [ 6.44547127e-01 -6.21554998e-01 -6.12210211e-01  3.40110954e-01]]


array([[ 1.,  2.,  3.,  4.],
       [ 7.,  8.,  9., 10.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [19., 20., 21., 22.]])

In [223]:
def solvehouse(A,b):
   
    house_QR(A)
    m,n=A.shape
    Q=np.eye(m)
    house_rev_accum(A,Q)
    R=np.zeros((m,n))
    for j in range(n):
        R[:j+1,j]=A[:j+1,j]
    x=np.empty(A.shape[0])
    b = np.matmul(Q.T,b)
    for i in range(A.shape[0]-1,-1,-1):
        x[i]=b[i]/A[i][i]
        for j in range(A.shape[0]-1,i,-1):
            x[i]-=x[j]*A[i][j]/A[i][i]
    return x  



A_1 = np.array([[149.4000,-3.7200,2.7600,2.9400],  
     [-9.9300,13.0000,-3.9600,-0.5500],   
     [-9.6200,3.2000,174.2000,8.3300],   
     [-2.9100,9.5600,0.3500,-57.0000]])
b_1 = np.array([354.120,-198.5200,970.9000,-4.4400])
x_1 = np.array([2,-12,6,-2],dtype = 'float64')
b_1 = np.reshape(b_1,(A_1.shape[0],-1))
A_2 = np.array([[69.8010,11.5380,-80.7660,-2.8800],   
    [550.0160,93.0030,-644.7280,-23.0400],     
    [137.8040,23.0760,-160.6330,-5.7600],     
      [7.5600,1.2420,-8.6940,-0.5430]])     
b_2 = np.array([-190.9320, -1612.0590, -392.6520, -23.8650])
b_2=np.reshape(b_2,(A_2.shape[0],-1))
x_2 = np.array([14,15,16,17],dtype = 'float64')
x_11 = solvehouse(A_1,b_1)
x_22 = solvehouse(A_2,b_2)
print('решение методом хаусхолдера для хорошо обусловленной матрицы',x_11)
print('решение методом хаусхолдера для плохо обусловленной матрицы',x_22)

print('1-норма  невязки  для первой матрицы = ', np.linalg.norm((x_11-x_1),1))
print('1-норма невязки  для второй матрицы = ', np.linalg.norm((x_22-x_2),1))
print('inf-норма  невязки  для первой матрицы = ', np.linalg.norm((x_11-x_1), np.inf))
print('inf-норма невязки  для второй матрицы = ', np.linalg.norm((x_22-x_2), np.inf))
print('абсолютная погрешность для первой = ', np.abs(x_11-x_1))
print('абсолютная погрешность для первой = ', np.abs(x_22-x_2))
print('относительная погрешность для первой = ', np.abs(x_11-x_1)/x_1)
print('относительная погрешность для первой = ', np.abs(x_22-x_2)/x_1)




решение методом хаусхолдера для хорошо обусловленной матрицы [  2. -12.   6.  -2.]
решение методом хаусхолдера для плохо обусловленной матрицы [13.99999947 14.99999579 15.99999895 16.9999999 ]
1-норма  невязки  для первой матрицы =  2.220446049250313e-16
1-норма невязки  для второй матрицы =  5.894383019011684e-06
inf-норма  невязки  для первой матрицы =  2.220446049250313e-16
inf-норма невязки  для второй матрицы =  4.2107234392574355e-06
абсолютная погрешность для первой =  [2.22044605e-16 0.00000000e+00 0.00000000e+00 0.00000000e+00]
абсолютная погрешность для первой =  [5.26337764e-07 4.21072344e-06 1.05268143e-06 1.04640389e-07]
относительная погрешность для первой =  [ 1.11022302e-16 -0.00000000e+00  0.00000000e+00 -0.00000000e+00]
относительная погрешность для первой =  [ 2.63168882e-07 -3.50893620e-07  1.75446904e-07 -5.23201944e-08]


In [214]:
def reverse(A):
#     A^(-1)*A=E
#  (1 2)   (x1 x2)  (1 0)
#  (3 4)   (x3 x4)  (0 1)
    X = []
    A_1 = np.copy(A)
    x = np.zeros(A.shape[1])
    for i in range(A.shape[1]):
        x[i] = 1
        A = np.copy(A_1)
        X.append(solvehouse(A,x))
        x[i] = 0
    return X  
A_1 = np.array([[149.4000,-3.7200,2.7600,2.9400],  
     [-9.9300,13.0000,-3.9600,-0.5500],   
     [-9.6200,3.2000,174.2000,8.3300],   
     [-2.9100,9.5600,0.3500,-57.0000]])
X_1=np.transpose(reverse(A_1))
print(X_1@A_1)
X_2=np.transpose(reverse(A_2))
print(X_2@A_2)
print('Число обусловленности первой матрицы = ', np.linalg.norm(A_1)*np.linalg.norm(X_1))
print('Число обусловленности второй матрицы = ', np.linalg.norm(A_2)*np.linalg.norm(X_2))

[[ 1.00000000e+00 -5.63785130e-18  1.76318378e-17  0.00000000e+00]
 [-3.66460334e-17  1.00000000e+00  1.51137783e-16 -6.76542156e-17]
 [ 1.90819582e-17  1.73472348e-18  1.00000000e+00 -6.93889390e-18]
 [ 6.93889390e-18  0.00000000e+00  2.77555756e-17  1.00000000e+00]]
[[ 1.00000000e+00 -1.38777878e-17  2.22044605e-16  3.81334233e-18]
 [ 8.32667268e-17  1.00000000e+00  5.32907052e-15  1.44578360e-16]
 [-4.85722573e-17 -2.77555756e-17  1.00000000e+00  2.92124723e-17]
 [ 1.94289029e-16  5.55111512e-17  3.55271368e-15  1.00000000e+00]]
Число обусловленности первой матрицы =  19.47294968490102
Число обусловленности второй матрицы =  11678.90351127004


In [217]:
def gauss_method(matrix, vector):
    n = len(matrix)
    for i in range(n):
        max_el = abs(matrix[i][i])
        max_row = i
        for k in range(i + 1, n):
            if abs(matrix[k][i]) > max_el:
                max_el = abs(matrix[k][i])
                max_row = k

        matrix[i], matrix[max_row] = matrix[max_row], matrix[i]
        vector[i], vector[max_row] = vector[max_row], vector[i]

        for k in range(i + 1, n):
            c = -matrix[k][i] / matrix[i][i]
            for j in range(i, n):
                if i == j:
                    matrix[k][j] = 0
                else:
                    matrix[k][j] += c * matrix[i][j]
            vector[k] += c * vector[i]

    x = [0 for _ in range(n)]
    for i in range(n - 1, -1, -1):
        x[i] = vector[i] / matrix[i][i]
        for k in range(i - 1, -1, -1):
            vector[k] -= matrix[k][i] * x[i]
    return x
A_1 = np.array([[149.4000,-3.7200,2.7600,2.9400],  
     [-9.9300,13.0000,-3.9600,-0.5500],   
     [-9.6200,3.2000,174.2000,8.3300],   
     [-2.9100,9.5600,0.3500,-57.0000]])
b_1 = np.array([354.120,-198.5200,970.9000,-4.4400])
x_1 = np.array([2,-12,6,-2],dtype = 'float64')
A_2 = np.array([[69.8010,11.5380,-80.7660,-2.8800],   
    [550.0160,93.0030,-644.7280,-23.0400],     
    [137.8040,23.0760,-160.6330,-5.7600],     
      [7.5600,1.2420,-8.6940,-0.5430]])     
b_2 = np.array([-190.9320, -1612.0590, -392.6520, -23.8650])
b_2=np.reshape(b_2,(A_2.shape[0],-1))
print(gauss_method(A_1,b_1))    
print(gauss_method(A_2,b_2)) #не решает   


[2.0, -12.0, 6.000000000000002, -2.0]
[array([nan]), array([nan]), array([nan]), array([nan])]


C:\Users\user\AppData\Local\Temp\ipykernel_16240\2249033413.py:25: RuntimeWarning: invalid value encountered in divide
  x[i] = vector[i] / matrix[i][i]


In [222]:
A_1 = np.array([[149.4000,-3.7200,2.7600,2.9400],  
     [-9.9300,13.0000,-3.9600,-0.5500],   
     [-9.6200,3.2000,174.2000,8.3300],   
     [-2.9100,9.5600,0.3500,-57.0000]])
b_1 = np.array([354.120,-198.5200,970.9000,-4.4400])
x_1 = np.array([2,-12,6,-2],dtype = 'float64')
A_2 = np.array([[69.8010,11.5380,-80.7660,-2.8800],   
    [550.0160,93.0030,-644.7280,-23.0400],     
    [137.8040,23.0760,-160.6330,-5.7600],     
      [7.5600,1.2420,-8.6940,-0.5430]])     
b_2 = np.array([-190.9320, -1612.0590, -392.6520, -23.8650])
b_2=np.reshape(b_2,(A_2.shape[0],-1))
np.linalg.solve(A_1,b_1)
np.linalg.solve(A_2,b_2)
# L U разложение

array([  2., -12.,   6.,  -2.])